### ISSUE TITLE
oc login fails with invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by bennetelli** [openshift/oc#1142]
Dear coworkers,

I am getting a invalid memory or nil pointer dereference error when trying to login to OpenShift via cli.

```
oc version
oc v3.11.0+20c5b86
kubernetes v1.10.0+b3b92b2
features: Basic-Auth GSSAPI Kerberos SPNEGO
```

```
go version
go version go1.18 linux/amd64
```

when trying to login via cli (oc login) I am getting this stacktrace:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x4145bc]

goroutine 1 [running]:
reflect.mapiternext(0x40?)
	/usr/lib/golang/src/runtime/map.go:1378 +0x19
github.com/openshift/origin/vendor/github.com/modern-go/reflect2.(*UnsafeMapIterator).UnsafeNext(0x0?)
	/builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/github.com/modern-go/reflect2/unsafe_map.go:136 +0x32
github.com/openshift/origin/vendor/github.com/json-iterator/go.(*sortKeysMapEncoder).Encode(0xc000755fb0, 0xc0000509a0, 0xc000727380)
	/builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/github.com/json-iterator/go/reflect_map.go:273 +0x335
github.com/openshift/origin/vendor/github.com/json-iterator/go.(*placeholderEncoder).Encode(0xc0001fe370?, 0xc95047?, 0xc000727398?)
	/builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/github.com/json-iterator/go/reflect.go:325 +0x22
github.com/openshift/origin/vendor/github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc00075f890, 0x213eb63?, 0xc000727380)
	/builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/github.com/json-iterator/go/reflect_struct_encoder.go:110 +0x56
github.com/openshift/origin/vendor/github.com/json-iterator/go.(*structEncoder).Encode(0xc00075f9e0, 0xc0001a6280?, 0xc000727380)
	/builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/github.com/json-iterator/go/reflect_struct_encoder.go:158 +0x652
github.com/openshift/origin/vendor/github.com/json-iterator/go.(*placeholderEncoder).Encode(0xc0001fe4e8?, 0xc95047?, 0xc000727398?)
	/builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/github.com/json-iterator/go/reflect.go:325 +0x22
github.com/openshift/origin/vendor/github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc00075fc50, 0x20b0423?, 0xc000727380)
	/builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/github.com/json-iterator/go/reflect_struct_encoder.go:110 +0x56
github.com/openshift/origin/vendor/github.com/json-iterator/go.(*structEncoder).Encode(0xc00075fcb0, 0xc0001fe620?, 0xc000727380)
	/builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/github.com/json-iterator/go/reflect_struct_encoder.go:158 +0x652
github.com/openshift/origin/vendor/github.com/json-iterator/go.(*sliceEncoder).Encode(0xc0007589d8, 0xc001343f48, 0xc000727380)
	/builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/github.com/json-iterator/go/reflect_slice.go:42 +0x30d
github.com/openshift/origin/vendor/github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc0007667e0, 0x20bc8c6?, 0xc000727380)
	/builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/github.com/json-iterator/go/reflect_struct_encoder.go:110 +0x56
github.com/openshift/origin/vendor/github.com/json-iterator/go.(*structEncoder).Encode(0xc0007668d0, 0x0?, 0xc000727380)
	/builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/github.com/json-iterator/go/reflect_struct_encoder.go:158 +0x652
github.com/openshift/origin/vendor/github.com/json-iterator/go.(*OptionalEncoder).Encode(0xc0001fe848?, 0x410025?, 0x2387c00?)
	/builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/github.com/json-iterator/go/reflect_optional.go:74 +0xa4
github.com/openshift/origin/vendor/github.com/json-iterator/go.(*onePtrEncoder).Encode(0xc000512b40, 0xc001343ef0, 0xc0001fe898?)
	/builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/github.com/json-iterator/go/reflect.go:213 +0x82
github.com/openshift/origin/vendor/github.com/json-iterator/go.(*Stream).WriteVal(0xc000727380, {0x246f080, 0xc001343ef0})
	/builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/github.com/json-iterator/go/reflect.go:93 +0x158
github.com/openshift/origin/vendor/github.com/json-iterator/go.(*frozenConfig).Marshal(0xc0000fe400, {0x246f080, 0xc001343ef0})
	/builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/github.com/json-iterator/go/config.go:296 +0xc9
github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).Encode(0xc00001f810?, {0x2d1cf98?, 0xc001343ef0?}, {0x2d0cca0, 0xc00077f7d0})
	/builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/runtime/serializer/json/json.go:226 +0x6d
github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/runtime/serializer/versioning.(*codec).Encode(0xc00020b0e0, {0x2d1cf48?, 0xc0011c4420}, {0x2d0cca0, 0xc00077f7d0})
	/builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/runtime/serializer/versioning/versioning.go:221 +0x7c6
github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/runtime.Encode({0x7fd298525c18, 0xc00020b0e0}, {0x2d1cf48, 0xc0011c4420})
	/builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/runtime/codec.go:46 +0x64
github.com/openshift/origin/vendor/k8s.io/client-go/tools/clientcmd.Write(...)
	/builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/client-go/tools/clientcmd/loader.go:426
github.com/openshift/origin/vendor/k8s.io/client-go/tools/clientcmd.WriteToFile({{0x0, 0x0}, {0x0, 0x0}, {0x0, 0xc00077e7e0}, 0xc00077f500, 0xc00077f5c0, 0xc00077f6b0, {0xc00140ca20, ...}, ...}, ...)
	/builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/client-go/tools/clientcmd/loader.go:406 +0xa8
github.com/openshift/origin/vendor/k8s.io/client-go/tools/clientcmd.ModifyConfig({0x2d36840, 0xc0000bd900}, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0xc0012aef30}, 0xc0012aef60, 0xc0012aef90, ...}, ...)
	/builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/client-go/tools/clientcmd/config.go:268 +0xb38
github.com/openshift/origin/pkg/oc/cli/login.(*LoginOptions).SaveConfig(0xc0001ff790)
	/builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/pkg/oc/cli/login/loginoptions.go:382 +0x227
github.com/openshift/origin/pkg/oc/cli/login.LoginOptions.Run({{0xc0012a5840, 0x34}, {0x0, 0x0}, 0x0, {0xc00071ac00, 0xa}, {0x0, 0x0}, {0xc001849280, ...}, ...})
	/builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/pkg/oc/cli/login/login.go:179 +0x38
github.com/openshift/origin/pkg/oc/cli/login.NewCmdLogin.func1(0xc000879400?, {0xc00113a460, 0x0, 0x2})
	/builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/pkg/oc/cli/login/login.go:59 +0x1c5
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).execute(0xc000879400, {0xc00113a400, 0x2, 0x2})
	/builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:760 +0x663
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000879180)
	/builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:846 +0x2dc
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:794
main.main()
	/builddir/build/BUILD/origin-20c5b86c88657888e4906ed7942b85515c650f96/_output/local/go/src/github.com/openshift/origin/cmd/oc/oc.go:70 +0x4db
```

**Comment by bennetelli** [comment]
Updated to oc client 4.10 and it works fine now. 

Not sure if you want to add a fix for v3. I will just leave the issue open so you can decide.
